version: '3.6'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./.env
    networks:
      - ndbk

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PW}
      ME_CONFIG_BASICAUTH_USERNAME: ${BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL_DOCKER}
    env_file:
      - ./.env
    networks:
      - ndbk

  web-app:
    container_name: web-app
    image: kinganduin1987/webapp-api-nosql:${TAGOS}
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      NODE_ENV: ${NODE_ENV}
      BASIC_AUTH_PW: ${BASIC_AUTH_PW}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_USER_SQL: ${DB_USER_SQL}
      DB_PWD_SQL: ${DB_PWD_SQL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MONGODB: ${MONGODB_DOCKER}
      MONGO: ${MONGO_DOCKER}
      MONGODBNAME: ${MONGODBNAME}
    env_file:
      - ./.env
    networks:
      - ndbk

volumes:
  mariadb:
  mongodb:

networks:
  ndbk:
