version: '3.6'

services:
  mariadb-ndbs:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - mariadb:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=mariadb
    - MYSQL_USER=maria
    - MYSQL_PASSWORD=password

  phpmyadmin-mariadb-ndbs:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
    - mariadb-ndbs
    environment:
    - PMA_HOST=mariadb-ndbs
    - PMA_PORT=3306
    - PMA_USER=maria
    - PMA_PASSWORD=password
    ports:
    - "3001:80"

  couchdb-ndbs:
    image: arm64v8/couchdb:latest
    restart: always
    environment:
    - COUCHDB_PASSWORD=couchdb
    - COUCHDB_USER=admin
    ports:
    - "5985:5984"
    
volumes:
  mariadb:

networks:
  ndbk: