version: '3.6'

services:
  mariadb-ndbs:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - mariadb:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=scenario_uber
    - MYSQL_USER=maria
    - MYSQL_PASSWORD=password
    ports:
    - 3306:3306

  phpmyadmin-mariadb-ndbs:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
    - mariadb-ndbs
    environment:
    - PMA_HOST=mariadb-ndbs
    - PMA_PORT=3306
    - PMA_USER=maria
    - PMA_PASSWORD=password
    - UPLOAD_LIMIT=500M
    ports:
    - "3001:80"

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
    
volumes:
  mariadb:
  postgresdb:

networks:
  ndbk: