version: '3.6'

services:
  mariadb10:
    image: mariadb:10.4.8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - mariadb:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=mariadb
    - MYSQL_USER=maria
    - MYSQL_PASSWORD=password

  phpmyadmin-mariadb:
    image: phpmyadmin/phpmyadmin:4.8.5
    restart: always
    depends_on:
    - mariadb10
    environment:
    - PMA_HOST=mariadb10
    - PMA_PORT=3306
    - PMA_USER=maria
    - PMA_PASSWORD=password
    ports:
    - "3001:80"

volumes:
  mariadb:

networks:
  ndbk: