version: '3.6'

services:
  mariadb-ndbs:
    container_name: mariadb-ndbs
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PWD_SQL}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${DB_USER_SQL}
      - MYSQL_PASSWORD=${DB_PWD_SQL}
    ports:
      - 3306:3306
    env_file:
      - ./.env
    networks:
      - ndbk

  phpmyadmin-mariadb-ndbs:
    container_name: phpmyadmin-mariadb-ndbs
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - mariadb-ndbs
    environment:
      - PMA_HOST=mariadb-ndbs
      - PMA_PORT=3306
      - PMA_USER=${DB_USER_SQL}
      - PMA_PASSWORD=${DB_PWD_SQL}
      - UPLOAD_LIMIT=500M
    ports:
      - '3001:80'
    env_file:
      - ./.env
    networks:
      - ndbk

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./.env
    networks:
      - ndbk

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PW}
      ME_CONFIG_BASICAUTH_USERNAME: ${BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL_DOCKER}
    env_file:
      - ./.env
    networks:
      - ndbk

volumes:
  mariadb:
  mongodb:

networks:
  ndbk:
